export interface VocabularyWord {
  /** UUID, generated by crypto.randomUUID() */
  id: string
  /** The original word or phrase */
  word: string
  /** The translated text */
  translation: string
  /** Page URL where the word was collected */
  contextUrl?: string
  /** Surrounding sentence context */
  contextText?: string
  /** ISO 639-3 source language code */
  sourceLanguage?: string
  /** ISO 639-3 target language code */
  targetLanguage?: string
  /** Memory rating: 1 = hardest, 5 = mastered */
  star: 1 | 2 | 3 | 4 | 5
  /** Timestamp when created (Date.now()) */
  createdAt: number
  /** Timestamp of last review */
  lastReviewedAt?: number
  /** How many times reviewed */
  reviewCount: number
  /** Optional user note */
  note?: string
}

/** Payload for adding a new vocabulary word */
export interface AddVocabularyWordPayload {
  word: string
  translation: string
  contextUrl?: string
  contextText?: string
  sourceLanguage?: string
  targetLanguage?: string
}

/** Payload for updating a vocabulary word */
export interface UpdateVocabularyWordPayload {
  id: string
  updates: Partial<Pick<VocabularyWord, "star" | "translation" | "note">>
}

/** Query options for listing vocabulary words */
export interface VocabularyQuery {
  limit?: number
  offset?: number
  sortBy?: "createdAt" | "star" | "word"
  sortOrder?: "asc" | "desc"
  search?: string
}

/** Response for a flashcard session */
export interface FlashcardSession {
  words: VocabularyWord[]
  total: number
}

/** Structured word definition returned by the dictionary REST API */
export interface WordDefinition {
  headword: string
  phoneticUK?: string
  phoneticUS?: string
  pos: string
  senses: Array<{
    number: string
    chineseDefinition: string
  }>
}
